# Generated by Django 2.2 on 2023-01-10 20:12

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20230111_0111'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, author=django.db.models.expressions.F('user')), name='unique_blocking'),
        ),
    ]
